# SPDX-License-Identifier: Apache-2.0
"""Audit exported TorchScript policy on G1-LongBoxPush-v0.

This intentionally avoids OnPolicyRunner. Use exported/policy.pt generated by WBC eval/train.
"""

import argparse
from pathlib import Path

import torch
from isaaclab.app import AppLauncher


parser = argparse.ArgumentParser(description="Audit exported G1 longbox push TorchScript policy.")
parser.add_argument("--task", type=str, default="G1-LongBoxPush-v0")
parser.add_argument("--policy", type=str, required=True, help="Path to exported/policy.pt TorchScript file.")
parser.add_argument("--num_envs", type=int, default=1)
parser.add_argument("--num_steps", type=int, default=500)
parser.add_argument("--print_every", type=int, default=100)
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import gymnasium as gym

import agile.rl_env.tasks  # noqa: F401
import agile.isaaclab_extras.monkey_patches  # noqa: F401
from agile.rl_env.rsl_rl import RslRlVecEnvWrapper
from isaaclab_tasks.utils import load_cfg_from_registry


def quat_yaw_wxyz(q: torch.Tensor) -> torch.Tensor:
    w, x, y, z = q[:, 0], q[:, 1], q[:, 2], q[:, 3]
    siny_cosp = 2.0 * (w * z + x * y)
    cosy_cosp = 1.0 - 2.0 * (y * y + z * z)
    return torch.atan2(siny_cosp, cosy_cosp)


def obs_for_torchscript(obs):
    # WBC exported policies usually expect a flat tensor.
    if isinstance(obs, torch.Tensor):
        return obs
    if isinstance(obs, dict) or (hasattr(obs, "values") and callable(obs.values)):
        return torch.cat([v.flatten(start_dim=1) for v in obs.values()], dim=-1)
    raise TypeError(f"Unsupported obs type for TorchScript policy: {type(obs)}")


def main():
    policy_path = Path(args_cli.policy)
    if not policy_path.exists():
        raise FileNotFoundError(f"Policy not found: {policy_path}")

    env_cfg = load_cfg_from_registry(args_cli.task, "env_cfg_entry_point")
    env_cfg.scene.num_envs = args_cli.num_envs

    gym_env = gym.make(args_cli.task, cfg=env_cfg, render_mode=None)
    env = RslRlVecEnvWrapper(gym_env)

    device = env.unwrapped.device
    policy = torch.jit.load(str(policy_path), map_location=device)
    policy.eval()

    env.reset()
    obs, _extras = env.get_observations()

    u = env.unwrapped
    robot = u.scene["robot"]
    box = u.scene["object"]

    box_x0 = box.data.root_pos_w[:, 0].clone()
    base_x0 = robot.data.root_pos_w[:, 0].clone()

    max_box_dx = torch.full((u.num_envs,), -1e9, device=u.device)
    min_robot_z = torch.full((u.num_envs,), 1e9, device=u.device)
    max_abs_box_yaw = torch.zeros((u.num_envs,), device=u.device)

    print("=== checkpoint_audit_start ===", flush=True)
    print(f"task={args_cli.task}", flush=True)
    print(f"policy={policy_path}", flush=True)
    print(f"num_envs={u.num_envs}", flush=True)
    print(f"num_steps={args_cli.num_steps}", flush=True)
    print(f"obs_type={type(obs)}", flush=True)
    print(f"box_pos0={box.data.root_pos_w[0].detach().cpu().tolist()}", flush=True)
    print(f"base_pos0={robot.data.root_pos_w[0].detach().cpu().tolist()}", flush=True)

    for step in range(args_cli.num_steps):
        with torch.inference_mode():
            obs_in = obs_for_torchscript(obs)
            actions = policy(obs_in)
            obs, _rew, _done, _extras = env.step(actions)

        box_pos = box.data.root_pos_w
        base_pos = robot.data.root_pos_w
        box_yaw = quat_yaw_wxyz(box.data.root_quat_w)

        box_dx = box_pos[:, 0] - box_x0
        base_dx = base_pos[:, 0] - base_x0

        max_box_dx = torch.maximum(max_box_dx, box_dx)
        min_robot_z = torch.minimum(min_robot_z, base_pos[:, 2])
        max_abs_box_yaw = torch.maximum(max_abs_box_yaw, torch.abs(box_yaw))

        if (step + 1) % args_cli.print_every == 0 or step == args_cli.num_steps - 1:
            rear_face_x = box_pos[0, 0] - 0.8
            base_to_rear = rear_face_x - base_pos[0, 0]
            print(
                f"step={step + 1} "
                f"box_dx={box_dx[0].item():.4f} "
                f"max_box_dx={max_box_dx[0].item():.4f} "
                f"base_dx={base_dx[0].item():.4f} "
                f"robot_z={base_pos[0, 2].item():.4f} "
                f"min_robot_z={min_robot_z[0].item():.4f} "
                f"box_yaw={box_yaw[0].item():.4f} "
                f"max_abs_box_yaw={max_abs_box_yaw[0].item():.4f} "
                f"base_to_rear={base_to_rear.item():.4f}",
                flush=True,
            )

    final_box_dx = box.data.root_pos_w[:, 0] - box_x0
    final_base_dx = robot.data.root_pos_w[:, 0] - base_x0
    final_yaw = quat_yaw_wxyz(box.data.root_quat_w)
    final_rear_face_x = box.data.root_pos_w[:, 0] - 0.8
    final_base_to_rear = final_rear_face_x - robot.data.root_pos_w[:, 0]

    print("=== checkpoint_audit_summary ===", flush=True)
    print(f"final_box_dx={final_box_dx[0].item():.4f}", flush=True)
    print(f"max_box_dx={max_box_dx[0].item():.4f}", flush=True)
    print(f"final_base_dx={final_base_dx[0].item():.4f}", flush=True)
    print(f"min_robot_z={min_robot_z[0].item():.4f}", flush=True)
    print(f"final_box_yaw={final_yaw[0].item():.4f}", flush=True)
    print(f"max_abs_box_yaw={max_abs_box_yaw[0].item():.4f}", flush=True)
    print(f"final_base_to_rear={final_base_to_rear[0].item():.4f}", flush=True)
    print("=== checkpoint_audit_done ===", flush=True)

    env.close()


if __name__ == "__main__":
    main()
    simulation_app.close()
